Repository MrLuit/EtherScamDB, pull requests merged in 2018-06, with the labels that each got.

#889 calchain.net + ethpays.me
  _data/scams.yaml
Labels: blacklist

#890 ethgive.me + more
  _data/scams.yaml
Labels: blacklist

#892 xn--myetherwllt-f7a75e.com
  _data/scams.yaml
Labels: blacklist

#894 ethpromo.io + more
  _data/scams.yaml
Labels: blacklist

#895 ethgw.info + more
  _data/scams.yaml
Labels: blacklist

#896 saferpayether.com + more
  _data/scams.yaml
Labels: blacklist

#897 kinetictokenform.typeform.com + xn--myetherwllt-r7a44e.com
  _data/scams.yaml
Labels: blacklist

#899 myetehrewallet.com + more
  _data/scams.yaml
Labels: blacklist

#900 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#901 idexmarket.io
  _data/scams.yaml
Labels: blacklist

#902 ethofficial.info + more
  _data/scams.yaml
Labels: blacklist

#903 keyfund.io + more
  _data/scams.yaml
Labels: blacklist

#904 eos-swap.com
  _data/scams.yaml
Labels: blacklist

#905 ethpromo.cc + more
  _data/scams.yaml
Labels: blacklist

#906 promotoeth.org
  _data/scams.yaml
Labels: blacklist

#909 eos-paperwallet.com + more
  _data/scams.yaml
Labels: blacklist

#910 eth-get.com + more
  _data/scams.yaml
Labels: blacklist

#911 idek.io + more
  _data/scams.yaml
Labels: blacklist

#912 bestethgift.com + collect.bestethgift.com
  _data/scams.yaml
Labels: blacklist

#913 idex-market.io + more
  _data/scams.yaml
Labels: blacklist

#916 telegram.vu + more
  _data/scams.yaml
Labels: blacklist

#917 myiteher.com + more
  _data/scams.yaml
Labels: blacklist

#918 etherskan.io + etherscan.ltd
  _data/scams.yaml
Labels: blacklist

#919 fantoms.foundation
  _data/scams.yaml
Labels: blacklist

#921 myetherwallat.co + more
  _data/scams.yaml
Labels: blacklist

#920 ethereum-bonus.com
  _data/scams.yaml
Labels: blacklist

#922 ethereum.website.tk + more
  _data/scams.yaml
Labels: blacklist

#923 get.ethpublic.com + more
  _data/scams.yaml
Labels: blacklist

#928 safe.ethxchanges.com + more
  _data/scams.yaml
Labels: blacklist

#926 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#930 xn--myethrwalett-8vb19c.net + more
  _data/scams.yaml
Labels: blacklist

#931 myethertrust.com
  _data/scams.yaml
Labels: blacklist

#932 etheroll.io
  _data/scams.yaml
Labels: blacklist

#933 xn--myetherrwalet-5hc.net + more
  _data/scams.yaml
Labels: blacklist

#935 xn--mythrwalet-smb0a15c.com + more
  _data/scams.yaml
Labels: blacklist

#937 xn--myetherwalle-mm5f.com + more
  _data/scams.yaml
Labels: blacklist

#938 kentra.tech + xn--myethrwalt-inbe64c.com
  _data/scams.yaml
Labels: blacklist

#940 bittrex-id.com
  _data/scams.yaml
Labels: blacklist

#942 idex-market.at + wallet-idex.net
  _data/scams.yaml
Labels: blacklist

#944 myighther.net + eteclum.org
  _data/scams.yaml
Labels: blacklist

#945 ethbonus.org
  _data/scams.yaml
Labels: blacklist

#947 creteprint-driveways.co.uk + more
  _data/scams.yaml
Labels: blacklist

#948 giveethers.info
  _data/scams.yaml
Labels: blacklist

#951 eth.blogmedium.top + more
  _data/scams.yaml
Labels: blacklist

#952 ethpromoaction.com + more
  _data/scams.yaml
Labels: blacklist

#954 ethergive.net
  _data/scams.yaml
Labels: blacklist

#956 airtake.info
  _data/scams.yaml
Labels: blacklist

#958 walleteos.io + more
  _data/scams.yaml
Labels: blacklist

#959 binance-giveaway.com
  _data/scams.yaml
Labels: blacklist

#961 welcome.promotionaleth.com
  _data/scams.yaml
Labels: blacklist

#962 hederahashgraph.tokenico.me + more
  _data/scams.yaml
Labels: blacklist

#963 getbigdeals.org + more
  _data/scams.yaml
Labels: blacklist

#964 ploloneix.com + more
  _data/scams.yaml
Labels: blacklist

#965 twitter.whitelist.json
  _data/twitter.whitelist.json
Labels: whitelist

#966 AbuseIPDB link
  _layouts/ip.html
  config.example.js
  run.js
Labels: enhancement

#968 giveawaypromo.byethost14.com + xn--myethrwllt-y4a7gf.com
  _data/scams.yaml
Labels: blacklist

#967 Added AirSwap domain to legit_urls.yaml
  _data/legit_urls.yaml
Labels: whitelist

#969 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#970 added to twitter.whitelist.json
  _data/twitter.whitelist.json
Labels: whitelist

#971 twitter.whitelist.json update
  _data/twitter.whitelist.json
Labels: whitelist

#972 Remove twitter whitelist duplicates
  _data/twitter.whitelist.json
Labels: duplicate, whitelist

#973 etherbonus.win + more
  _data/scams.yaml
Labels: blacklist

#974 index-markels.com
  _data/scams.yaml
Labels: blacklist

#976 eth-claim.org + more
  _data/scams.yaml
Labels: blacklist

#979 new twitter whitelists
  _data/twitter.json
Labels: whitelist

#980 eoscountdown.co + more
  _data/scams.yaml
Labels: blacklist

#982 BokkyPooBah
  _data/twitter.json
Labels: whitelist

#983 Update twitter.json
  _data/twitter.json
Labels: blacklist

#984 today-ethereum.com + ethnow.org
  _data/scams.yaml
Labels: blacklist

#985 updated twitter and removed comma
  _data/twitter.json
Labels: whitelist

#986 update twitter.json
  _data/twitter.json
Labels: whitelist

#988 index-marketz.com + more
  _data/scams.yaml
Labels: blacklist

#989 ethereumgw.org + epromo.cc
  _data/scams.yaml
Labels: blacklist

#990 Update twitter.json
  _data/twitter.json
Labels: blacklist

#991 updated twitter.json
  _data/twitter.json
Labels: whitelist

#992 update
  _data/twitter.json
Labels: whitelist

#993 added twitters from an influencers list
  _data/twitter.json
Labels: whitelist

#994 updated twitter whitelist
  _data/twitter.json
Labels: whitelist

#995 giveawaypromo.byethost14.com + more
  _data/scams.yaml
Labels: blacklist

#996 cz_binatce
  _data/twitter.json
Labels: blacklist

#997 iddexmarket.com + more
  _data/scams.yaml
Labels: blacklist

#999 updated twitter json
  _data/twitter.json
Labels: whitelist

#1001 indexmarkett-corp.com + more
  _data/scams.yaml
Labels: blacklist

#1002 updated twitter.json
  _data/twitter.json
Labels: whitelist

#1004 ethereum-prize.com + more
  _data/scams.yaml
Labels: blacklist

#1005 myetherwallett.net + more
  _data/scams.yaml
Labels: blacklist

#1006 xn--myeterwallet-o0b.com
  _data/scams.yaml
Labels: blacklist

#1009 elon-shares.com
  _data/scams.yaml
Labels: blacklist

#1010 Update twitter.json
  _data/twitter.json
Labels: whitelist

#1008 Update added whitelisted accounts twitter.json
  _data/twitter.json
Labels: whitelist

#1011 get.perfecteth.com + more
  _data/scams.yaml
Labels: blacklist

#1015 ethereum-claim.org + more
  _data/scams.yaml
Labels: blacklist

#1016 ethshare.org + more
  _data/scams.yaml
Labels: blacklist

#1013 update twitter.json
  _data/twitter.json
Labels: whitelist

#1019 xn--coinbas-z8a.tk
  _data/scams.yaml
Labels: blacklist

#1018 Added @mises to twitter
  _data/twitter.json
Labels: whitelist

#1022 waves-platform.net + more
  _data/scams.yaml
Labels: blacklist

#1023 remove duplicate
  _data/scams.yaml
Labels: blacklist

#1024 Added Ivan and Zquestz to whitelist
  _data/twitter.json
Labels: whitelist

#1026 c-kamowski.fr + more
  _data/scams.yaml
Labels: blacklist

#1027 Update twitter.json
  _data/twitter.json
Labels: whitelist

#1028 get.personaleth.com + more
  _data/scams.yaml
Labels: blacklist

#1029 idexmarketllc.com + more
  _data/scams.yaml
Labels: blacklist

#1012 Fixed eth address Search
  _layouts/search.html
  _static/js/search.js
Labels: enhancement

#1030 Update twitter.json
  _data/twitter.json
Labels: whitelist

#1033 ethaction.io + more
  _data/scams.yaml
Labels: blacklist

#1034 event-eth.org + giveawaypromo.org
  _data/scams.yaml
Labels: blacklist

#1035 eos-platform.net + more
  _data/scams.yaml
Labels: blacklist

#1037 Update twitter.json
  _data/twitter.json
Labels: whitelist

#1038 indexmaker-network.com + more
  _data/scams.yaml
Labels: blacklist

#1039 Update twitter.json
  _data/twitter.json
Labels: whitelist

#1040 eosauthority.info + more
  _data/scams.yaml
Labels: blacklist

#1043 e.airdropeos.com
  _data/scams.yaml
Labels: blacklist

#1044 get.ethsupport.net + more
  _data/scams.yaml
Labels: blacklist

#1046 myeostrust.com + more
  _data/scams.yaml
Labels: blacklist

#1045 Updated twitter.json
  _data/twitter.json
Labels: whitelist

#1047 xn--eosauthorty-wcb.com + more
  _data/scams.yaml
Labels: blacklist

#1049 ethereum.odyssey.center
  _data/scams.yaml
Labels: blacklist

#1048 Add drinkYourOJ to Twitter whitelist
  _data/twitter.json
Labels: whitelist

#1050 give-ethprize.com + more
  _data/scams.yaml
Labels: blacklist

#1051 myetherwalett.000webhostapp.com + more
  _data/scams.yaml
Labels: blacklist

#1052 ethextra.net
  _data/scams.yaml
Labels: blacklist

#1053 ethe.mediumblog.top
  _data/scams.yaml
Labels: blacklist

#1055 ethereum-platform.org + more
  _data/scams.yaml
Labels: blacklist

#1056 ethereum-event.com + ethereum-giveaway.safe-eth.top
  _data/scams.yaml
Labels: blacklist

#1057 freeethpromo.com
  _data/scams.yaml
Labels: blacklist

#1058 eos-authority.com + myethrawallet.com
  _data/scams.yaml
Labels: blacklist

#1059 musk-shares.com + more
  _data/scams.yaml
Labels: blacklist

#1060 ethe.mediumblog.top
  _data/scams.yaml
Labels: blacklist

#1061 ethereumdrop.info + more
  _data/scams.yaml
Labels: blacklist

#1062 Update twitter.json
  _data/twitter.json
Labels: whitelist

#1066 telegram.market
  _data/scams.yaml
Labels: blacklist

#1064 wallet.eostoolkits.io
  _data/scams.yaml
Labels: blacklist

#1067 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#1068 ethaway.com + more
  _data/scams.yaml
Labels: blacklist

#1069 xn--eosauthorty-jzb.com + more
  _data/scams.yaml
Labels: blacklist

#1070 eosauthorithy.com + ethereumanniversary.org
  _data/scams.yaml
Labels: blacklist

#1071 validbtc.com + more
  _data/scams.yaml
Labels: blacklist

#1072 myehferwallet.com + more
  _data/scams.yaml
Labels: blacklist

#1074 Added "Neodium Network"
  _data/legit_urls.yaml
Labels: whitelist

#1075 QuadrantAssets
  _data/twitter.json
Labels: whitelist

#1077 myethswallets.info
  _data/scams.yaml
Labels: blacklist

#1078 eossauthorithy.com
  _data/scams.yaml
Labels: blacklist

#1079 eossauthorithy.com + more
  _data/scams.yaml
Labels: blacklist

#1080 teslaforfree.wordpress.com + more
  _data/scams.yaml
Labels: blacklist
