Repository MrLuit/EtherScamDB, pull requests merged in 2018-02, with the labels that each got.

#490 adhive.net & tokensale.adhive.net
  _data/scams.yaml
Labels: blacklist

#489 Add Parity (client and company) to trusted urls
  _data/legit_urls.yaml
Labels: whitelist

#491 trx.foundation
  _data/scams.yaml
Labels: blacklist

#495 fusion.tokencrowdsale.online
  _data/scams.yaml
Labels: blacklist

#494 Adding https://nucleus.vision
  _data/legit_urls.yaml
  _data/scams.yaml
Labels: blacklist, whitelist

#496 sale-earn.com
  _data/scams.yaml
Labels: blacklist

#498 xn--yethewalle-to2exkhi.com
  _data/scams.yaml
Labels: blacklist

#500 Fake MEW sites
  _data/scams.yaml
Labels: blacklist

#501 ethexploit.org
  _data/scams.yaml
Labels: blacklist

#502 dock.promo & dock.so
  _data/scams.yaml
Labels: blacklist

#503 jibreltoken.in
  _data/scams.yaml
Labels: blacklist

#504 nucleus-vision.cc + more
  _data/scams.yaml
Labels: blacklist

#505 xn--myetheralle-7b9ezl.com
  _data/scams.yaml
Labels: blacklist

#506 icotoken-current.top
  _data/scams.yaml
Labels: blacklist

#499 Adding https://remme.live
  _data/legit_urls.yaml
  _data/scams.yaml
Labels: blacklist, whitelist

#507 vechain-foundation.com + more
  _data/scams.yaml
Labels: blacklist

#508 openplatform.tech
  _data/scams.yaml
Labels: blacklist

#509 metamaskgiveaway.xyz
  _data/scams.yaml
Labels: blacklist

#510 fake dock crowdsale sites
  _data/scams.yaml
Labels: blacklist

#511 xn--es-8bb.com xn--myetherallt-pl9elw.com + more
  _data/scams.yaml
Labels: blacklist

#513 fin-trux.com + more
  _data/scams.yaml
Labels: blacklist

#514 xn--polonx-0va26t.com
  _data/scams.yaml
Labels: blacklist

#515 jiocoins.io
  _data/scams.yaml
Labels: blacklist

#516 seele.promo seele-ico.eu seele-ico.pro
  _data/scams.yaml
Labels: blacklist

#517 xn--binnce-5nf.com xn--biace-4l1bb.com
  _data/scams.yaml
Labels: blacklist

#519 forkdeita.github.io
  _data/scams.yaml
Labels: blacklist

#520 ton.fund
  _data/scams.yaml
Labels: blacklist

#521 polyswarm.bid
  _data/scams.yaml
Labels: blacklist

#522 sale-dock.com
  _data/scams.yaml
Labels: blacklist

#523 polyswarm.in
  _data/scams.yaml
Labels: blacklist

#524 seele-token.pro + more
  _data/scams.yaml
Labels: blacklist

#525 myethervallet.pro
  _data/scams.yaml
Labels: blacklist

#526 dock.network
  _data/scams.yaml
Labels: blacklist

#527 dock-io.org
  _data/scams.yaml
Labels: blacklist

#528 polyswarm.pw
  _data/scams.yaml
Labels: blacklist

#529 dock.click dock-tokensale.eu
  _data/scams.yaml
Labels: blacklist

#530 polyswarm.ru
  _data/scams.yaml
Labels: blacklist

#531 dflnlty.org
  _data/scams.yaml
Labels: blacklist

#532 tron-foundation.org + more
  _data/scams.yaml
Labels: blacklist

#533 xn--yeterwallet-bm8eym.com
  _data/scams.yaml
Labels: blacklist

#534 add myetherwallet.com to legit sites
  _data/legit_urls.yaml
Labels: whitelist

#535 el-petro-coin.com
  _data/scams.yaml
Labels: blacklist

#536 xn--myethewalle-w48erh.com + myetherwallett.site
  _data/scams.yaml
Labels: blacklist

#542 xn--myetheralle-jb9exm.com + more
  _data/scams.yaml
Labels: blacklist

#545 xn--metherwalle-jb9ejq.com xn--coindek-s73c.com
  _data/scams.yaml
Labels: blacklist

#546 address-transfer-confirmation.droppages.com
  _data/scams.yaml
Labels: blacklist

#547 akasha-world.com
  _data/scams.yaml
Labels: blacklist

#548 6khb.payment-checker-ethereum-id-bslyftexjuwcgv8.filesusr.com
  _data/scams.yaml
Labels: blacklist

#550 neonexchanges.org
  _data/scams.yaml
Labels: blacklist

#551 gonetwork-airdrop.co
  _data/scams.yaml
Labels: blacklist

#555 forkdelta.io + more
  _data/scams.yaml
Labels: blacklist

#556 vechain-foundation.org + more
  _data/scams.yaml
Labels: blacklist

#557 dfinlty.org
  _data/scams.yaml
Labels: blacklist

#558 transfer-address-confirmation.droppages.com + more
  _data/scams.yaml
Labels: blacklist

#559 add hawen[.]io and havven[.]xyz
  _data/scams.yaml
Labels: blacklist

#563 tokensale-adhive.com
  _data/scams.yaml
Labels: blacklist

#564 ipsx.promo
  _data/scams.yaml
Labels: blacklist

#565 dflinity.org
  _data/scams.yaml
Labels: blacklist

#566 xn--coindek-873c.com + more
  _data/scams.yaml
Labels: blacklist

#569 tron-online.org + more
  _data/scams.yaml
Labels: blacklist

#570 meganfoxloveyou.com + more
  _data/scams.yaml
Labels: blacklist

#571 ico-havven.org & tokensale-havven.in
  _data/scams.yaml
Labels: blacklist

#572 nucelus.vision
  _data/scams.yaml
Labels: blacklist

#573 havven.top
  _data/scams.yaml
Labels: blacklist

#574 havvenio.com
  _data/scams.yaml
Labels: blacklist
