Repository MrLuit/EtherScamDB, pull requests merged in 2018-07, with the labels that each got.

#1082 idext.market + more
  _data/scams.yaml
Labels: blacklist

#1081 ethereumstash.org
  _data/scams.yaml
Labels: blacklist

#1083 ethtwitter.com + more
  _data/scams.yaml
Labels: blacklist

#1085 Added celebration-eth.com
  _data/scams.yaml
Labels: blacklist

#1086 Update twitter.json
  _data/twitter.json
Labels: whitelist

#1087 dapp.doubledouble.io + more
  _data/scams.yaml
Labels: blacklist

#1088 remove duplicate + more scams
  _data/scams.yaml
Labels: blacklist

#1089 event-eth.org + more
  _data/scams.yaml
Labels: blacklist

#1090 myethertrust.com address
  _data/scams.yaml
Labels: blacklist

#1091 pumphash.com + more
  _data/scams.yaml
Labels: blacklist

#1092 hitbtc-login.com + more
  _data/scams.yaml
Labels: blacklist

#1094 xrp-address.org
  _data/scams.yaml
Labels: blacklist

#1096 eth-gift.club + more
  _data/scams.yaml
Labels: blacklist

#1097 geocities.ws full path
  _data/scams.yaml
Labels: blacklist

#1098 eosauthority.com.globatalent.network
  _data/scams.yaml
Labels: blacklist

#1099 ethbig.net + more
  _data/scams.yaml
Labels: blacklist

#1101 added protocols for update script
  _data/scams.yaml
Labels: blacklist

#1102 xn--ethrdelta-iib.com + more
  _data/scams.yaml
Labels: blacklist

#1103 trx.claims + more
  _data/scams.yaml
Labels: blacklist

#1104 node82.btc-giveaway.info + more
  _data/scams.yaml
Labels: blacklist

#1105 myeleherwaret.com + meytherwellat.com
  _data/scams.yaml
Labels: blacklist

#1106 claim.ether33.online + more
  _data/scams.yaml
Labels: blacklist

#1107 bit-airdrop.com + more
  _data/scams.yaml
Labels: blacklist

#1108 ethereumfoundationgift.tumblr.com + more
  _data/scams.yaml
Labels: blacklist

#1110 etherdeltha.info + forcdelta.com
  _data/scams.yaml
Labels: blacklist

#1111 tokenaway.com + more
  _data/scams.yaml
Labels: blacklist

#1113 myertnerwalletr.com + more
  _data/scams.yaml
Labels: blacklist

#1117 ethmore.net + more
  _data/scams.yaml
Labels: blacklist

#1118 mmyetlherwallett.com
  _data/scams.yaml
Labels: blacklist

#1119 ethbonus.me + more
  _data/scams.yaml
Labels: blacklist

#1121 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#1122 ethcryptopromos.com + more
  _data/scams.yaml
Labels: blacklist

#1123 meyetherwealletr.com + myerhterwallett.com
  _data/scams.yaml
Labels: blacklist

#1125 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#1124 add ethsoffer.com - twitter spambot
  _data/scams.yaml
Labels: blacklist

#1126 safe.eth10000.org + more
  _data/scams.yaml
Labels: blacklist

#1129 Fix og-image logo
  _static/img/logo.png
Labels: enhancement

#1132 ethereumpromote.wixsite.com + more
  _data/scams.yaml
Labels: blacklist

#1135 myehtrerwallett.com + more
  _data/scams.yaml
Labels: blacklist

#1136 bittrexl.com + more
  _data/scams.yaml
Labels: blacklist

#1134 hydrogen-raindrop.bitballoon.com + more
  _data/scams.yaml
Labels: blacklist

#1137 5000eth-giving.online
  _data/scams.yaml
Labels: blacklist

#1138 ethcontracts.org + more
  _data/scams.yaml
Labels: blacklist

#1139 indexmarkket-site.com + more
  _data/scams.yaml
Labels: blacklist

#1140 ethmore.live + more
  _data/scams.yaml
Labels: blacklist

#1141 ethpromotion.info + more
  _data/scams.yaml
Labels: blacklist

#1146 added new scams: event-eth.com
  _data/scams.yaml
Labels: blacklist

#1147 token-emrify.com + more
  _data/scams.yaml
Labels: blacklist

#1149 myetherwallet.com.rootsign.icu + more
  _data/scams.yaml
Labels: blacklist

#1148 cashaaprivate.com/airdrop/
  _data/scams.yaml
Labels: blacklist

#1151 neotracler.co + more
  _data/scams.yaml
Labels: blacklist

#1152 idixmarket.info + coinbaise.com
  _data/scams.yaml
Labels: blacklist

#1153 walletico.com
  _data/scams.yaml
Labels: blacklist

#1131 Added some security tips
  _layouts/scamdomain.html
  _static/css/scam.css
  run.js
Labels: enhancement

#1145 Fixed search for neutral eth addresses
  _static/js/search.js
Labels: bugfix

#1154 refundcontract-etherwallet.net + idexr.market
  _data/scams.yaml
Labels: blacklist

#1156 index-markett-network.com + more
  _data/scams.yaml
Labels: blacklist

#1157 idexmarket.me + more
  _data/scams.yaml
Labels: blacklist

#1160 ether-event.com + more
  _data/scams.yaml
Labels: blacklist

#1161 idexchange.pro
  _data/scams.yaml
Labels: blacklist

#1158 Add tests
  .travis.yml
  package-lock.json
  package.json
  tests/validate_data.js
Labels: enhancement

#1159 Logging
  package-lock.json
  package.json
  run.js
  update.js
Labels: enhancement

#1163 blvonance.com + more
  _data/scams.yaml
Labels: blacklist

#1165 www-bitfinex.com
  _data/scams.yaml
Labels: blacklist

#1166 ethzerdelta.com + more
  _data/scams.yaml
Labels: blacklist

#1162 myetherwalletmessage.signauth.icu/signmsg.html
  _data/scams.yaml
Labels: blacklist

#1168 login.blockchaim.co
  _data/scams.yaml
Labels: blacklist

#1170 mcafee.promo + more
  _data/scams.yaml
Labels: blacklist

#1171 coinssafe.org
  _data/scams.yaml
Labels: blacklist

#1172 getethernow.org + more
  _data/scams.yaml
Labels: blacklist

#1185 sociall.ooo + more
  _data/scams.yaml
Labels: blacklist

#1186 idex-markt-roosen-gmbh.com + more
  _data/scams.yaml
Labels: blacklist

#1187 stellar-w.com + bitfinex.im
  _data/scams.yaml
Labels: blacklist

#1188 dailycurrency.ml + more
  _data/scams.yaml
Labels: blacklist

#1189 giveaway-binance.com + more
  _data/scams.yaml
Labels: blacklist

#1190 bitfanex.com + more
  _data/scams.yaml
Labels: blacklist

#1191 promo.etherpay.site + more
  _data/scams.yaml
Labels: blacklist

#1194 eosgas.co + more
  _data/scams.yaml
Labels: blacklist

#1198 myetherwallet.com.api5.icu + more
  _data/scams.yaml
Labels: blacklist

#1199 claimprize.org + more
  _data/scams.yaml
Labels: blacklist

#1200 myetherwallet-hydrosign.space + more
  _data/scams.yaml
Labels: blacklist

#1201 descentx.com + more
  _data/scams.yaml
Labels: blacklist

#1202 idex-market.biz.pl + more
  _data/scams.yaml
Labels: blacklist

#1203 ethcryptocomp.cx + more
  _data/scams.yaml
Labels: blacklist

#1204 bitfilinex.com
  _data/scams.yaml
Labels: blacklist

#1205 blgem.blogspot.com + more
  _data/scams.yaml
Labels: blacklist

#1206 kuciorn.hosstinger.info + more
  _data/scams.yaml
Labels: blacklist

#1207 eth-giveaway.space + more
  _data/scams.yaml
Labels: blacklist

#1208 blovrnance.com + more
  _data/scams.yaml
Labels: blacklist

#1211 fantom-foundation.de + more
  _data/scams.yaml
Labels: blacklist

#1209 Update scams.yaml
  _data/scams.yaml
Labels: blacklist
