Repository MrLuit/EtherScamDB, pull requests merged in 2018-05, with the labels that each got.

#781 update https://t.me/daostackchannelANN
  _data/scams.yaml
Labels: blacklist

#782 eosreward.io + more
  _data/scams.yaml
Labels: blacklist

#783 axpire.tech
  _data/scams.yaml
Labels: blacklist

#784 Added more addresses for quarkchain-ico.io
  _data/scams.yaml
Labels: blacklist

#786 get-ethereum.org
  _data/scams.yaml
Labels: blacklist

#787 meythcrrwallet.ru.com + more
  _data/scams.yaml
Labels: blacklist

#789 blockchaihs.info
  _data/scams.yaml
Labels: blacklist

#790 cdnsfiles.com
  _data/scams.yaml
Labels: blacklist

#791 add fake medium article
  _data/scams.yaml
Labels: blacklist

#792 tronlabsnetwork.com + more
  _data/scams.yaml
Labels: blacklist

#793 eth-giveaway.updog.co
  _data/scams.yaml
Labels: blacklist

#794 5000eth.org
  _data/scams.yaml
Labels: blacklist

#795 giveavvay10000eth.host
  _data/scams.yaml
Labels: blacklist

#796 eth-giveaway.co.nf
  _data/scams.yaml
Labels: blacklist

#798 verifiedeth.com + more
  _data/scams.yaml
Labels: blacklist

#799 myetherwallet.access-checker.com + more
  _data/scams.yaml
Labels: blacklist

#800 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#679 Added case-insensitivity and visual indicator of new search
  _layouts/search.html
  _static/js/search.js
Labels: 0-priority, enhancement

#801 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#802 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#803 add fake daostack google doc
  _data/scams.yaml
Labels: blacklist

#804 add daostack.onuniverse.com
  _data/scams.yaml
Labels: blacklist

#805 get-ethereum.ml + more
  _data/scams.yaml
Labels: blacklist

#806 Update scams.yaml
  _data/scams.yaml
Labels: blacklist

#807 kinecosystem.io
  _data/scams.yaml
Labels: blacklist

#808 i-idex.market + forkdelta.net
  _data/scams.yaml
Labels: blacklist

#809 promo-give-ethereum.org + more
  _data/scams.yaml
Labels: blacklist

#810 update telegram.com
  _data/scams.yaml
Labels: blacklist

#811 xn--tbtc-upa94a.com + more
  _data/scams.yaml
Labels: blacklist

#812 xn--myetherwallt-ovb.net + idexmarkets.com
  _data/scams.yaml
Labels: blacklist

#813 collect.ethforyou.com + more
  _data/scams.yaml
Labels: blacklist

#815 musk-party-gifts.updog.co + more
  _data/scams.yaml
Labels: blacklist

#816 telegram-token.io + icostats.io
  _data/scams.yaml
Labels: blacklist

#817 privcoin.io + more
  _data/scams.yaml
Labels: blacklist

#818 xn--polonix-17a.com + xn--tro-k5y.com
  _data/scams.yaml
Labels: blacklist

#819 xn--bifinex-fb4c.com + more
  _data/scams.yaml
Labels: blacklist

#814 add dav.icocrowdsale.io
  _data/scams.yaml
Labels: blacklist

#820 xn--mytherwallet-5vb.net + more
  _data/scams.yaml
Labels: blacklist

#823 quarkchain.live
  _data/scams.yaml
Labels: blacklist

#824 etherfree.tech
  _data/scams.yaml
Labels: blacklist

#825 quarkchain.de suspected address + etherums-givingaway.atspace.tv
  _data/scams.yaml
Labels: blacklist

#827 zclassiccoins.com + more
  _data/scams.yaml
Labels: blacklist

#828 5000ethereum.online + more
  _data/scams.yaml
Labels: blacklist

#829 eth-giveaway.today + more
  _data/scams.yaml
Labels: blacklist

#830 quarkchains.io + more
  _data/scams.yaml
Labels: blacklist

#831 tokenairdrop.typeform.com + more
  _data/scams.yaml
Labels: blacklist

#832 quarkchain.pl + more
  _data/scams.yaml
Labels: blacklist

#833 waves-ethereum-eth.org
  _data/scams.yaml
Labels: blacklist

#835 m342edium.ethersforme.net + more
  _data/scams.yaml
Labels: blacklist

#836 ebtweinfinance.com + more
  _data/scams.yaml
Labels: blacklist

#838 promo-eths.com + nathanielpopper.promo-eths.com
  _data/scams.yaml
Labels: blacklist

#839 walleteos.org
  _data/scams.yaml
Labels: blacklist

#840 claimeth.epizy.com
  _data/scams.yaml
Labels: blacklist

#841 eth-promo.net + more
  _data/scams.yaml
Labels: blacklist

#842 biitbay.com + more
  _data/scams.yaml
Labels: blacklist

#844 5000eth-promo.com + more
  _data/scams.yaml
Labels: blacklist

#845 etherdelta.githiub.io + more
  _data/scams.yaml
Labels: blacklist

#846 ethgift.org + hydroraindrop.typeform.com
  _data/scams.yaml
Labels: blacklist

#847 ethconfirm.info + more
  _data/scams.yaml
Labels: blacklist

#848 get.ico-eth.org + more
  _data/scams.yaml
Labels: blacklist

#850 mew-ehterwallat.com + more
  _data/scams.yaml
Labels: blacklist

#851 eth4everyone.com + ethtransaction.ezyro.com address
  _data/scams.yaml
Labels: blacklist

#852 tron-block.com + more
  _data/scams.yaml
Labels: blacklist

#853 xn--mytherwallet-fvb.net + more
  _data/scams.yaml
Labels: blacklist

#854 givefree-eth.com + more
  _data/scams.yaml
Labels: blacklist

#856 wallets-ether.com
  _data/scams.yaml
Labels: blacklist

#857 secure375446884521.safeethpay.com + more
  _data/scams.yaml
Labels: blacklist

#858 claim-eth.com + more
  _data/scams.yaml
Labels: blacklist

#859 quarkchain.pub
  _data/scams.yaml
Labels: blacklist

#860 myerherwallet.tk + more
  _data/scams.yaml
Labels: blacklist

#861 ethpromo.org + more
  _data/scams.yaml
Labels: blacklist

#863 lendium.tech + more
  _data/scams.yaml
Labels: blacklist

#864 mycrypto.promo + more
  _data/scams.yaml
Labels: blacklist

#865 tomochain.tech + more
  _data/scams.yaml
Labels: blacklist

#866 got-eth.com
  _data/scams.yaml
Labels: blacklist

#867 air-eos.com
  _data/scams.yaml
Labels: blacklist

#868 ethgiveaway.zkr.kr + more
  _data/scams.yaml
Labels: blacklist

#869 coinbase.pro-fork.com
  _data/scams.yaml
Labels: blacklist

#870 eoslaunch.io
  _data/scams.yaml
Labels: blacklist

#871 10000eth.net
  _data/scams.yaml
Labels: blacklist

#873 ethg.me + more
  _data/scams.yaml
Labels: blacklist

#874 ether-giveaway.net + more
  _data/scams.yaml
Labels: blacklist

#875 coinbaseverifier.com
  _data/scams.yaml
Labels: blacklist

#879 tron-online.info + more
  _data/scams.yaml
Labels: blacklist

#881 xn--myethrwalt-zmbt05c.com + more
  _data/scams.yaml
Labels: blacklist

#877 ethers.cz + ethergate.space
  _data/scams.yaml
Labels: blacklist

#882 ethn.cc
  _data/scams.yaml
Labels: blacklist

#885 xn--mytherwalt-smbh17c.com
  _data/scams.yaml
Labels: blacklist

#878 add email phishing attempt
  _data/scams.yaml
Labels: blacklist

#884 Add phishing google doc
  _data/scams.yaml
Labels: blacklist

#886 ethtopromo.org + more
  _data/scams.yaml
Labels: blacklist

#887 Footer changes
  _layouts/default.html
  _static/css/general.css
  _static/img/powered-by-mycrypto.png
Labels: enhancement

#888 idex-info.com + more
  _data/scams.yaml
Labels: blacklist
