Repository MrLuit/EtherScamDB, pull requests merged in 2019-01, with the labels that each got.

#1405 biboxpr.icu
  _data/scams.yaml
Labels: blacklist

#1406 cryptobridge.su + xrp-giveaway.com
  _data/scams.yaml
Labels: blacklist

#1407 newyearcrypto.blogspot.com + more
  _data/scams.yaml
Labels: blacklist

#1408 gowincoin.com + more
  _data/scams.yaml
Labels: blacklist

#1409 Please add @kevinkoosk to whitelist
  _data/twitter.json
Labels: whitelist

#1410 idex.ru.com + more
  _data/scams.yaml
Labels: blacklist

#1411 karatbars-affiliate-bonus.com + more
  _data/scams.yaml
Labels: blacklist

#1412 myetherwallet-dfz.space + more
  _data/scams.yaml
Labels: blacklist

#1413 etcv-wallet.com + wallet.hydroproject.io
  _data/scams.yaml
Labels: blacklist

#1415 dex-hbiglobal.info + more
  _data/scams.yaml
Labels: blacklist

#1417 janbinancexrp.blogspot.com + more
  _data/scams.yaml
Labels: blacklist

#1418 btc-promo.net + more
  _data/scams.yaml
Labels: blacklist

#1416 Added route for security.txt
  .gitignore
  run.js
Labels: enhancement

#1421 ltcpro.live + more
  _data/scams.yaml
Labels: blacklist

#1422 localethereum.com.support-ticket-report.com
  _data/scams.yaml
Labels: blacklist

#1423 eloncity.sale + more
  _data/scams.yaml
Labels: blacklist

#1424 Add @mysticryuujin
  _data/twitter.json
Labels: whitelist

#1427 bttpromotion.github.io + more
  _data/scams.yaml
Labels: blacklist

#1428 buteringift.com + more
  _data/scams.yaml
Labels: blacklist

#1429 circlemix.io + more
  _data/scams.yaml
Labels: blacklist

#1430 btcaim.com + more
  _data/scams.yaml
Labels: blacklist

#1431 cryptoexcoins.com + more
  _data/scams.yaml
Labels: blacklist

#1432 idexmarket.website + more
  _data/scams.yaml
Labels: blacklist

#1433 myetheresswallet.com
  _data/scams.yaml
Labels: blacklist
